#!/bin/sh
cd "`dirname $0`"
compiler='java -jar tools/closure-compiler-r2388.jar'

files_outer="./src/sis/ajui.js ./src/sis/ajui/Elements.js ./src/sis/ajui/Utils.js "
files_scoped="`find ./src/core/ -name *.js` `find ./src/sis/ajui/widget/ -name *.js` `find ./src/sis/ajui/windows/ -name *.js`"
out='build/libajui.js'

echo '// generated by' `basename $0` > $out
$compiler --process_jquery_primitives --js $files_outer >> $out
#cat $files_outer >> $out
echo -n "(function ($, jQuery, AdminJUI_Elements, undefined) {" >> $out
$compiler --process_jquery_primitives --js $files_scoped >> $out
#cat $files_scoped >> $out
echo "})(jQuery, jQuery, sis.ajui.Elements);" >> $out

